name = "navsphere-data"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"



[env.production.vars]
# GitHub OAuth App 配置
GITHUB_ID = "Ov23liUU710eX4Pj3gU5"
# GitHub 仓库配置  
GITHUB_OWNER = "222shuai"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
# NextAuth 配置
NEXTAUTH_URL = "https://navsphere.shuai2.eu.org/api/auth"
NEXT_PUBLIC_API_URL="https://navsphere.shuai2.eu.org"
